# Generated by Django 6.0 on 2025-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(default=None, max_length=100, verbose_name='Descrição'),
        ),
    ]
